name = "URIs2"
uuid = "f1e0c292-0b4a-4077-b638-9f4b059c84ea"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "0.1.0"

[extras]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test", "TestItemRunner"]
